sudo: true
git:
    depth: 3
language: cpp
compiler: gcc
os: 
  - osx
  - linux
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      - george-edison55-precise-backports # cmake 3.x
    packages:
      - cmake
      - cmake-data
      - gcc-4.8
      - g++-4.8
      - libglu1-mesa-dev
      - xorg-dev
      - libasound2-dev

install:
  - echo $TRAVIS_OS_NAME
  # LINUX
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 50; fi

script:
  - echo $TRAVIS_OS_NAME
  - git --version

  # LINUX
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then python fips set config yakc-linux-make-unittest; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then python fips clean all; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then python fips make Test; fi
  - if [ "$TRAVIS_OS_NAME" == "linux" ]; then python fips run Test; fi

  # OSX
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then python fips set config yakc-osx-make-unittest; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then python fips clean all; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then python fips make Test; fi
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then python fips run Test; fi

